# Generated by Django 4.2.3 on 2023-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('closed', 'Завершена'), ('started', 'Запущена')], default='created', max_length=7, verbose_name='Статус'),
        ),
    ]
