# Generated by Django 4.2.3 on 2023-08-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
    ]
