# Generated by Django 4.2.3 on 2023-08-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailing_time_mailing_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='mail_response',
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('ok', 'Исполнена'), ('failed', 'Провалена')], max_length=6, verbose_name='Статус попытки'),
        ),
    ]
